name: Publish to Nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - id: tag
        uses: Viostream/github-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write out version
        run: |
          version=${{ steps.tag.outputs.new_tag }}
          sed -i 's|<version>.*</version>|<version>'${version#v}'</version>|' src/NHibernate.Json/NHibernate.Json.nuspec
      - name: Build
        run: dotnet build -c Release src/NHibernate.Json/NHibernate.Json.csproj
      - name: Package
        run: |
          version=${{ steps.tag.outputs.new_tag }}
          dotnet pack -c Release src/NHibernate.Json/NHibernate.Json.csproj -o . -p:PackageVersion=${version#v}
      - name: Nuget push
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
